package com.docker.atsea.ws.orders;

import com.docker.atsea.ws.students.Student;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;
import java.util.Map;

/**
 * Examples code for spring boot with CXF services. Hello is the interface for
 * sayHello interface. This class was generated by Apache CXF 3.1.0
 * 2015-05-18T13:02:03.098-05:00 Generated source version: 3.1.0
 */
@WebService
public interface Order {

    @WebMethod
    int createOrder(@XmlElement(required=true, nillable=false) com.docker.atsea.model.Order order);

    @WebMethod
    int deleteOrder(@XmlElement(required=true, nillable=false) Integer orderId);

    @WebMethod
    Map<Integer, com.docker.atsea.model.Order> getOrders();
}