package com.docker.atsea.ws.orders;

import com.docker.atsea.ws.students.Student;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;
import java.util.Map;

/**
 * Examples code for spring boot with CXF services. Hello is the interface for
 * sayHello interface. This class was generated by Apache CXF 3.1.0
 * 2015-05-18T13:02:03.098-05:00 Generated source version: 3.1.0
 */
@WebService(targetNamespace = "http://service.ws.sample.order/", name = "Order")
public interface Order {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createOrder",
            targetNamespace = "http://service.ws.sample.order/",
            className = "sample.ws.service.order.createOrder")
    @WebMethod(action = "urn:CreateOrder")
    @ResponseWrapper(localName = "createOrderResponse",
            targetNamespace = "http://service.ws.sample.order/",
            className = "sample.ws.service.order.CreateOrderResponse")
    int createOrder(@WebParam(name = "order", targetNamespace = "") com.docker.atsea.model.Order order);

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteOrder",
            targetNamespace = "http://service.ws.sample.order/",
            className = "sample.ws.service.order.deleteOrder")
    @WebMethod(action = "urn:DeleteOrder")
    @ResponseWrapper(localName = "deleteOrderResponse",
            targetNamespace = "http://service.ws.sample.order/",
            className = "sample.ws.service.order.deleteOrderResponse")
    int deleteOrder(@WebParam(name = "orderId", targetNamespace = "") Integer orderId);

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getOrders",
            targetNamespace = "http://service.ws.sample.order/",
            className = "sample.ws.service.order.getOrders")
    @WebMethod(action = "urn:GetOrders")
    @ResponseWrapper(localName = "getOrderResponse",
            targetNamespace = "http://service.ws.sample.order/",
            className = "sample.ws.service.order.GetOrderResponse")public
    Map<Integer, com.docker.atsea.model.Order> getOrders();
}